org.gradle.jvmargs=-Xmx6144M -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.jvm.target.validation.mode=warning
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
org.gradle.jvmargs=-Xmx1536M -Djava.io.tmpdir=/home/user/flex_reminder_app/android/temp_build