// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KjjFJmc9BO42giswiMzjBPq5h8MQr9c',
    appId: '1:587023219031:web:d724d76f94f5fe8770e612',
    messagingSenderId: '587023219031',
    projectId: 'flex-reminder',
    authDomain: 'flex-reminder.firebaseapp.com',
    storageBucket: 'flex-reminder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_CqIRNOa2u-KTJ5v4KrwDQgp27JaGuA',
    appId: '1:587023219031:android:fcda1454e2cd5c2970e612',
    messagingSenderId: '587023219031',
    projectId: 'flex-reminder',
    storageBucket: 'flex-reminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4IBY3f58EMdaFi-KwYhdXPv9bGq9ptQ',
    appId: '1:587023219031:ios:d046339621af495d70e612',
    messagingSenderId: '587023219031',
    projectId: 'flex-reminder',
    storageBucket: 'flex-reminder.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCounter',
  );

}