// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvppJIurtbX99wZpLd5uYdjoqCIY05z6Q',
    appId: '1:1038373651011:web:43426d3da28031c94acaf6',
    messagingSenderId: '1038373651011',
    projectId: 'flex-reminders-app',
    authDomain: 'flex-reminders-app.firebaseapp.com',
    storageBucket: 'flex-reminders-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDiatYxR5UxZGt9gtttgTFrpu7l9xUIXU',
    appId: '1:1038373651011:android:a9b748f04d03e0f84acaf6',
    messagingSenderId: '1038373651011',
    projectId: 'flex-reminders-app',
    storageBucket: 'flex-reminders-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4rg2ndUz8nj7EVOzeUySktB5P1ulKOPc',
    appId: '1:1038373651011:ios:0a2feb7d58afe8da4acaf6',
    messagingSenderId: '1038373651011',
    projectId: 'flex-reminders-app',
    storageBucket: 'flex-reminders-app.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCounter',
  );

}